-- MySQL Script generated by MySQL Workbench
-- Thu May 23 17:45:27 2019
-- Model: football-league    Version: 1.1
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ekstraklasa
--
-- UTF8 - UTF8_POLISH_CI
-- 
-- Dawid Bitner
-- Marcin Krupa
-- Databases
-- Silesian University of Technology - Faculty of Applied Mathematics
-- 2018/2019
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ekstraklasa` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `ekstraklasa` ;

-- -----------------------------------------------------
-- Table `ekstraklasa`.`clubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekstraklasa`.`clubs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(30) NOT NULL,
  `founded` YEAR(4) NULL,
  `active` ENUM("ekstraklasa", "other league", "doesn't exist") NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_clubs_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_clubs_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ekstraklasa`.`coaches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekstraklasa`.`coaches` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `dateofbirth` DATE NULL,
  `nationality` VARCHAR(45) NULL,
  `club` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coaches_clubs1_idx` (`club` ASC),
  CONSTRAINT `fk_coaches_clubs1`
    FOREIGN KEY (`club`)
    REFERENCES `ekstraklasa`.`clubs` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ekstraklasa`.`crests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekstraklasa`.`crests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `image` LONGBLOB NULL,
  `club` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_crests_UNIQUE` (`id` ASC),
  INDEX `fk_crests_clubs1_idx` (`club` ASC),
  CONSTRAINT `fk_crests_clubs1`
    FOREIGN KEY (`club`)
    REFERENCES `ekstraklasa`.`clubs` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ekstraklasa`.`kits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekstraklasa`.`kits` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `home` VARCHAR(45) NULL,
  `away` VARCHAR(45) NULL,
  `clubcolours` VARCHAR(45) NULL,
  `club` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_kits_UNIQUE` (`id` ASC),
  INDEX `fk_kits_clubs1_idx` (`club` ASC),
  UNIQUE INDEX `club_UNIQUE` (`club` ASC),
  CONSTRAINT `fk_kits_clubs1`
    FOREIGN KEY (`club`)
    REFERENCES `ekstraklasa`.`clubs` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ekstraklasa`.`stadiums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekstraklasa`.`stadiums` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `capacity` MEDIUMINT UNSIGNED NULL,
  `buildyear` YEAR NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_stadiums_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ekstraklasa`.`clubs_has_stadiums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekstraklasa`.`clubs_has_stadiums` (
  `clubs_id_clubs` INT UNSIGNED NOT NULL,
  `stadiums_id_stadiums` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`clubs_id_clubs`, `stadiums_id_stadiums`),
  INDEX `fk_clubs_has_stadiums_stadiums1_idx` (`stadiums_id_stadiums` ASC),
  INDEX `fk_clubs_has_stadiums_clubs1_idx` (`clubs_id_clubs` ASC),
  CONSTRAINT `fk_clubs_has_stadiums_clubs1`
    FOREIGN KEY (`clubs_id_clubs`)
    REFERENCES `ekstraklasa`.`clubs` (`id`),
  CONSTRAINT `fk_clubs_has_stadiums_stadiums1`
    FOREIGN KEY (`stadiums_id_stadiums`)
    REFERENCES `ekstraklasa`.`stadiums` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ekstraklasa`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekstraklasa`.`players` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `dateofbirth` DATE NULL,
  `position` ENUM("goalkeeper", "defender", "midfielder", "striker") NOT NULL,
  `height` TINYINT UNSIGNED NULL,
  `weight` TINYINT UNSIGNED NULL,
  `nationality` VARCHAR(45) NULL,
  `club` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `id_currentplayers_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_players_clubs1_idx` (`club` ASC),
  CONSTRAINT `fk_players_clubs1`
    FOREIGN KEY (`club`)
    REFERENCES `ekstraklasa`.`clubs` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ekstraklasa`.`seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekstraklasa`.`seasons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `leaguename` VARCHAR(45) NOT NULL,
  `year` VARCHAR(9) NOT NULL,
  `1stplace` INT UNSIGNED NOT NULL,
  `2ndplace` INT UNSIGNED NOT NULL,
  `3thplace` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtable1_UNIQUE` (`id` ASC),
  INDEX `test_idx` (`1stplace` ASC, `2ndplace` ASC, `3thplace` ASC),
  CONSTRAINT `seasons_clubs`
    FOREIGN KEY (`1stplace` , `2ndplace` , `3thplace`)
    REFERENCES `ekstraklasa`.`clubs` (`id` , `id` , `id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ekstraklasa`.`domesticcups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekstraklasa`.`domesticcups` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `winner` INT UNSIGNED NOT NULL,
  `runnerupo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_domesticcup_UNIQUE` (`id` ASC),
  INDEX `domesticcup_clubs_idx` (`winner` ASC, `runnerupo` ASC),
  CONSTRAINT `domesticcup_clubs`
    FOREIGN KEY (`winner` , `runnerupo`)
    REFERENCES `ekstraklasa`.`clubs` (`id` , `id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;